export * from './create-cinema-body.interface';
export * from './update-cinema-body.interface';
export * from './create-cinema-hall-body.interface';
export * from './uppdate-cinema-hall-body.interface';
export * from './create-seat-body.interface';
export * from './cinema-repository.interface';
export * from './cinema-hall-repository.interface';
export * from './row-repository.interface';
export * from './seat-repository.interface';
